name = "SpeedrunPack"
author = "interp"
version = "mc1.20.4-v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7513765a15c5c094eee3550e4a590192ec5d999ca1d3df22137ac47c6717bf5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"
