name = "SpeedrunPack 1.14.4"
author = "interp"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d51aa80feb795a9350ee4f878331c0fee58994ef5da09f2c9683eaccd0b69650"

[versions]
fabric = "0.14.22"
minecraft = "1.14.4"
