name = "SpeedrunPack 1.18.2"
author = "interp"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "727e80d2f9c543f139b6c64c9bca74ad904117b8498e094d2c82a7541ba8de86"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
