name = "SpeedrunPack"
author = "interp"
version = "mc1.21-v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3778e343a7ec6d3b6c6b70490480be81306283ec03d763b0a66b23632329a521"

[versions]
fabric = "0.16.2"
minecraft = "1.21"
