name = "[SSG] SpeedrunPack"
author = "interp"
version = "mc1.16.1-v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c946fed97564d5457f57dd73b881f83920da8217a64d31490b3fad7012e998"

[versions]
fabric = "0.16.2"
minecraft = "1.16.1"
