name = "[SSG] SpeedrunPack"
author = "interp"
version = "mc1.16.1-v4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57ab92e4b18d53831aec7a38cee193d7389929b6c73faca2d4796a13d48e858f"

[versions]
fabric = "0.16.2"
minecraft = "1.16.1"
