name = "SpeedrunPack"
author = "interp"
version = "mc1.19.4-v3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c337ffcf6ea2d2129f75ccdddac2b08c5467a5e6d447127ec081ddf59b6a912b"

[versions]
fabric = "0.15.11"
minecraft = "1.19.4"
