name = "SpeedrunPack"
author = "interp"
version = "mc1.16.1-v4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a517d89819861149f20d90841735c028faeb3099084ed1fe1c9c5d601286c06"

[versions]
fabric = "0.16.2"
minecraft = "1.16.1"
